# Generated by Django 4.2.6 on 2023-11-11 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('arrived', models.DateTimeField(null=True)),
                ('price', models.IntegerField()),
                ('destiny_nation', models.CharField(max_length=50)),
                ('origin_nation', models.CharField(max_length=50)),
                ('origin_checkpoint', models.CharField(max_length=50)),
                ('destiny_checkpoint', models.CharField(max_length=50)),
                ('user_bison', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bison_orders', to=settings.AUTH_USER_MODEL)),
                ('user_citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Carriage',
            fields=[
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.service', verbose_name='ID')),
                ('pick_up', models.DateTimeField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='services.service', verbose_name='ID')),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('guide_number', models.AutoField(auto_created=True, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_nation', models.CharField(max_length=50)),
                ('current_checkpoint', models.CharField(max_length=50)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('destiny_nation__in', ['NACION DEL AIRE', 'NACION DEL FUEGO', 'NACION DE LA TIERRA', 'NACION DEL AGUA'])), name='valid_destiny_nation'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('origin_nation__in', ['NACION DEL AIRE', 'NACION DEL FUEGO', 'NACION DE LA TIERRA', 'NACION DEL AGUA'])), name='valid_origin_nation'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('origin_checkpoint__in', ['TRIBU AGUA DEL NORTE', 'TRIBU AGUA DEL SUR', 'TRIBU AIRE DEL NORTE', 'TRIBU AIRE DEL ESTE', 'TRIBU AIRE DEL OESTE', 'TRIBU AIRE DEL SUR', 'BA SING SE', 'ABADIA', 'GAIPAN', 'SI WONG', 'CAPITAL NACION DEL FUEGO', 'SHU JING'])), name='valid_origin_checkpoint'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('destiny_checkpoint__in', ['TRIBU AGUA DEL NORTE', 'TRIBU AGUA DEL SUR', 'TRIBU AIRE DEL NORTE', 'TRIBU AIRE DEL ESTE', 'TRIBU AIRE DEL OESTE', 'TRIBU AIRE DEL SUR', 'BA SING SE', 'ABADIA', 'GAIPAN', 'SI WONG', 'CAPITAL NACION DEL FUEGO', 'SHU JING'])), name='valid_destiny_checkpoint'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(check=models.Q(('weight__gte', 1), ('weight__lte', 500)), name='valid_weight'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(check=models.Q(('length__gte', 1), ('length__lte', 1000)), name='valid_length'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(check=models.Q(('width__gte', 1), ('width__lte', 1000)), name='valid_width'),
        ),
        migrations.AddConstraint(
            model_name='package',
            constraint=models.CheckConstraint(check=models.Q(('height__gte', 1), ('height__lte', 1000)), name='valid_height'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.CheckConstraint(check=models.Q(('current_nation__in', ['NACION DEL AIRE', 'NACION DEL FUEGO', 'NACION DE LA TIERRA', 'NACION DEL AGUA'])), name='valid_current_nation'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.CheckConstraint(check=models.Q(('current_checkpoint__in', ['TRIBU AGUA DEL NORTE', 'TRIBU AGUA DEL SUR', 'TRIBU AIRE DEL NORTE', 'TRIBU AIRE DEL ESTE', 'TRIBU AIRE DEL OESTE', 'TRIBU AIRE DEL SUR', 'BA SING SE', 'ABADIA', 'GAIPAN', 'SI WONG', 'CAPITAL NACION DEL FUEGO', 'SHU JING'])), name='valid_current_checkpoint'),
        ),
    ]
