# Generated by Django 4.2.6 on 2023-11-14 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='arrived',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
