# Generated by Django 4.2.6 on 2023-11-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_type_service_valid_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='route',
            field=models.CharField(blank=True),
        ),
    ]
