# Generated by Django 4.2.6 on 2023-11-18 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_service_type_service_valid_type'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='guide',
            name='valid_current_nation',
        ),
        migrations.RemoveConstraint(
            model_name='guide',
            name='valid_current_checkpoint',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='valid_destiny_nation',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='valid_origin_nation',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='valid_origin_checkpoint',
        ),
        migrations.RemoveConstraint(
            model_name='service',
            name='valid_destiny_checkpoint',
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.CheckConstraint(check=models.Q(('current_nation__in', ['Nación del Aire', 'Nación del Fuego', 'Nación de la Tierra', 'Nación del Agua'])), name='valid_current_nation'),
        ),
        migrations.AddConstraint(
            model_name='guide',
            constraint=models.CheckConstraint(check=models.Q(('current_checkpoint__in', ['Tribu agua del norte', 'Tribu agua del sur', 'Tribu aire del norte', 'Tribu aire del este', 'Tribu aire del oeste', 'Tribu aire del sur', 'Ba Sing Se', 'Abadía', 'Gaipan', 'Si Wong', 'Capital nación del fuego', 'Shu Jing'])), name='valid_current_checkpoint'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('destiny_nation__in', ['Nación del Aire', 'Nación del Fuego', 'Nación de la Tierra', 'Nación del Agua'])), name='valid_destiny_nation'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('origin_nation__in', ['Nación del Aire', 'Nación del Fuego', 'Nación de la Tierra', 'Nación del Agua'])), name='valid_origin_nation'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('origin_checkpoint__in', ['Tribu agua del norte', 'Tribu agua del sur', 'Tribu aire del norte', 'Tribu aire del este', 'Tribu aire del oeste', 'Tribu aire del sur', 'Ba Sing Se', 'Abadía', 'Gaipan', 'Si Wong', 'Capital nación del fuego', 'Shu Jing'])), name='valid_origin_checkpoint'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(check=models.Q(('destiny_checkpoint__in', ['Tribu agua del norte', 'Tribu agua del sur', 'Tribu aire del norte', 'Tribu aire del este', 'Tribu aire del oeste', 'Tribu aire del sur', 'Ba Sing Se', 'Abadía', 'Gaipan', 'Si Wong', 'Capital nación del fuego', 'Shu Jing'])), name='valid_destiny_checkpoint'),
        ),
    ]
